id: P006901
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6254
  title: གསུང་རྩོམ། མགོན་པོ་ཚེ་བརྟན།
  author: ''
  volumes:
    41703c84630344d0a2749b9c45e40af1:
      image_group_id: I1KG13599
      title: ''
      volume_number: 1
      total_pages: 196
